name: Render Remotion Video

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm' # 🔹 Caching otomatis untuk pnpm store

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store  # 🔹 Direktori cache pnpm
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Puppeteer Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxrandr2 libgbm1 libxtst6 libpango-1.0-0 libcairo2 libgdk-pixbuf2.0-0
      
      - name: Render Video
        run: pnpm run render

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: remotion-video
          path: out/video.mp4
          retention-days: 7

      - name: Upload Render Log
        uses: actions/upload-artifact@v4
        with:
          name: render-log
          path: render.log
          retention-days: 7
